// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5d74nDqhRgUHaRWvhjnssggmjQTbibh8',
    appId: '1:754387683815:web:8c3eac958f12a936e19542',
    messagingSenderId: '754387683815',
    projectId: 'campus-event-9daee',
    authDomain: 'campus-event-9daee.firebaseapp.com',
    databaseURL: 'https://campus-event-9daee-default-rtdb.firebaseio.com',
    storageBucket: 'campus-event-9daee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCycjO5cAjXK5efpamhro7zZrwwF3ipxuY',
    appId: '1:754387683815:android:25f6136dd5ca5898e19542',
    messagingSenderId: '754387683815',
    projectId: 'campus-event-9daee',
    databaseURL: 'https://campus-event-9daee-default-rtdb.firebaseio.com',
    storageBucket: 'campus-event-9daee.firebasestorage.app',
  );
}
